In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv("final_data.csv")
data.drop(["Unnamed: 0","Id"],axis=1,inplace=True)
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.4           2.9            1.4           0.2  Iris-setosa
3            5.0           3.4            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
le=LabelEncoder()
data["Species"] = le.fit_transform(data["Species"])

In [7]:
x_train,x_test,y_train,y_test = train_test_split(data.iloc[:,:-1],data.iloc[:,-1],test_size=0.2)
y_train.value_counts()

1    47
2    43
0    14
Name: Species, dtype: int64

In [8]:
y_test.value_counts()

2    11
0     9
1     6
Name: Species, dtype: int64

In [15]:
import xgboost as xgb
from sklearn.metrics import accuracy_score,confusion_matrix

In [10]:
xgb_cls=xgb.XGBClassifier(objective="multiclass:softmax",num_class=3)
xgb_cls.fit(x_train,y_train)


XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_class=3, num_parallel_tree=1,
              objective='multi:softprob', predictor='auto', random_state=0, ...)

In [12]:
preds=xgb_cls.predict(x_test)
preds

array([0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 1, 0, 0, 2, 2, 1, 0, 0, 2, 0, 2, 1,
       0, 2, 2, 1], dtype=int64)

In [14]:
y_test.values

array([0, 1, 2, 2, 2, 1, 0, 0, 2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 2, 0, 1, 1,
       0, 2, 2, 1])

In [16]:
accuracy_score(y_test,preds)

0.8461538461538461

In [17]:
confusion_matrix(y_test,preds)

array([[9, 0, 0],
       [0, 5, 1],
       [0, 3, 8]], dtype=int64)